# Generated by Django 4.0.6 on 2022-08-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_app', '0003_alter_bird_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='data',
        ),
    ]
