# Generated by Django 4.0.6 on 2022-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_app', '0005_remove_bird_user_position_bird_user_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='data',
            field=models.JSONField(default={'data': 'empty'}),
        ),
    ]
