# Generated by Django 4.0.6 on 2022-08-17 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_app', '0006_bird_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='bird_name',
            field=models.CharField(default='noname', max_length=255, validators=[django.core.validators.MinLengthValidator(1, 'This field cannot be blank.')]),
        ),
    ]
