# Generated by Django 4.0.6 on 2022-08-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_app', '0007_bird_bird_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='data',
        ),
    ]
