# Generated by Django 4.0.6 on 2023-10-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_app', '0009_bird_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='user',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='bird',
            name='date_confirmed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
