# Generated by Django 4.0.6 on 2023-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_app', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
